// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.PhoneNumberValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("detectedCountry")]
        public string DetectedCountry { get; set; }

        [JsonProperty("countryName")]
        public string CountryName { get; set; }

        [JsonProperty("countrycode")]
        public long? Countrycode { get; set; }

        [JsonProperty("numberNational")]
        public long? NumberNational { get; set; }

        [JsonProperty("extension")]
        public object Extension { get; set; }

        [JsonProperty("isValid")]
        public bool? IsValid { get; set; }

        [JsonProperty("isMobile")]
        public bool? IsMobile { get; set; }

        [JsonProperty("isVoip")]
        public bool? IsVoip { get; set; }

        [JsonProperty("isDisposable")]
        public bool? IsDisposable { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("formatted")]
        public Formatted Formatted { get; set; }

        [JsonProperty("riskScore")]
        public long? RiskScore { get; set; }

        [JsonProperty("riskLevel")]
        public string RiskLevel { get; set; }
    }

    public partial class Formatted
    {
        [JsonProperty("international")]
        public string International { get; set; }

        [JsonProperty("national")]
        public string National { get; set; }

        [JsonProperty("rfc")]
        public string Rfc { get; set; }

        [JsonProperty("e164")]
        public string E164 { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
